replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/ivoxa-form-dev/my-repo-dev/expense-ui-dev
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets:
  - name: gcp-secret

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: dev.ivoxa.ai
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dev.ivoxa.ai
      secretName: expense-ui-tls

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: 8080

readinessProbe:
  httpGet:
    path: /
    port: 8080

autoscaling:
  enabled: false