apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: expense-dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: expense_db
  MYSQL_USER: expense_user
  MYSQL_PASSWORD: expense_pass