replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/ivoxa-form-dev/my-repo-dev/expense-ui-dev
  tag: "dev-ef95a29123358ebcc0772a0b8e4913b29e179689"
  pullPolicy: Always

imagePullSecrets:
  - name: gcp-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

container:
  port: 8080 
    

livenessProbe: null
readinessProbe: null

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: dev.ivoxa.ai
      paths:
        - path: /
          pathType: Prefix

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

  tls:
    - hosts:
        - dev.ivoxa.ai
      secretName: dev-ivoxa-tls

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 15

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"