name: Dev Deploy

on:
 push:
  branches:
    - dev

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: us-central1
  SERVICE: expense-ui-dev
  REPO: my-repo-dev
  IMAGE: expense-ui-dev

jobs:
  build:
    name: Build and Deploy DEV
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker
          run: |
            gcloud auth configure-docker $REGION-docker.pkg.dev

      # Build docker Image
      - name: BUild Image
          run: |
            docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:${{ github.sha}} .

    # push Docker image
      - name: PUSH Image
          run : |
           docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:${{ github.sha}}


      - name: Deploy to Cloud Run (DEV)
        run: |
          gcloud run deploy $SERVICE \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated