name: Dev Deploy

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: us-central1
  CLUSTER: nirmal
  CLUSTER_ZONE: us-central1-a
  REPO: my-repo-dev
  UI_IMAGE: expense-ui-dev
  API_IMAGE: expense-api-dev
  NAMESPACE: expense-dev

jobs:
  build:
    name: Build and Deploy DEV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #  Authenticate to GCP
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      #  Setup gcloud
      - name: set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      #  Install plugin 
      - name: Install GKE auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      # 4. Enable plugin ✅
      - name: Enable plugin
        run: |
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV


      #  Connect to GKE
      - name:  Get GKE Crdentials
        run: |
          gcloud container clusters get-credentials $CLUSTER --zone $CLUSTER_ZONE --project $PROJECT_ID

      # COnfigure Docker
      - name: Configure Docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev
    
      # Build frontend image
      - name: Build Frontend Image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$UI_IMAGE:dev-${{ github.sha }} ./frontend

      # Push frontend Image
      - name: Push Frontend Image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$UI_IMAGE:dev-${{ github.sha }}

      # Build API image
      - name: Build Backend Image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$API_IMAGE:dev-${{ github.sha }} ./backend

      # Push API Image
      - name: Push Backend Image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$API_IMAGE:dev-${{ github.sha }}

      #  Deploy using Helm
      - name:  Helm Frontend Upgrade (Deploy)
        run: |
          helm upgrade --install expense-frontend-dev .\k8s\expense-frontend-chart --namespace $NAMESPACE --create-namespace -f .\k8s\expense-frontend-chart\dev-values.yaml --set image.tag=dev-${{ github.sha }}

      - name:  Helm Backend Upgrade (Deploy)
        run: |
          helm upgrade --install expense-backend-dev .\k8s\expense-backend-chart --namespace $NAMESPACE --create-namespace -f .\k8s\expense-backend-chart\dev-values.yaml --set image.tag=dev-${{ github.sha }}


