name: SonarQube Scan

on:
  push:
    branches:
      - main
jobs:
  sonar:
    name: Sonar Qube Analysis
    runs-on: self-hosted

    steps:
      - name: checout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=nirmal-test
            -Dsonar.sources=.
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL }}